name: fileit-devcontainer
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    network_mode: bridge
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "127.0.0.1:10000:10000"
    command:
      azurite
      --blobHost 0.0.0.0