name: fileit-devcontainer
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      AZURE_FUNCTIONS_ENVIRONMENT: Development
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
      ServiceBus: Endpoint=sb://emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    command: azurite --loose --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --silent --inMemoryPersistence #-l /data 
    network_mode: service:api
    # volumes:
    #   - azurite-data:/data
    

  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    environment:
      SQL_SERVER: sqledge  
      MSSQL_SA_PASSWORD: "123qwe!@#QWE"
      ACCEPT_EULA: "Y"
    depends_on:
      - sqledge

  sqledge:
        container_name: "sqledge"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "123qwe!@#QWE"

# volumes:
#   azurite-data: